apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: solr-operator
  template:
    metadata:
      labels:
        name: solr-operator
    spec:
      containers:
        - name: solr-operator
          image: previousnext/solr-operator
          command:
          - solr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
